spring:
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/fingrow?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:fingrow}
    password: ${DB_PASSWORD:fingrow123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    show-sql: true
    
  # OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:your-kakao-client-id}
            client-secret: ${KAKAO_CLIENT_SECRET:your-kakao-client-secret}
            redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/oauth/callback/kakao}
  
# SQL
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
server:
  port: 8080

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
  packages-to-scan: com.fingrow

# JWT 설정
jwt:
  secret: ${JWT_SECRET:fingrow-jwt-secret-key-for-token-generation-and-validation-2024}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY:3600}  # 1시간
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY:1209600}  # 2주

# 금융감독원 설정
finlife:
  api:
    key: ${FINLIFE_API_KEY:YOUR_API_KEY_HERE}  # 환경변수로 API 키 설정
    base-url: https://finlife.fss.or.kr/finlifeapi
    timeout:
      connect: 5000
      read: 10000

# ETF 설정
krx:
  api:
    key: ${KRX_API_KEY}
