spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fingrow?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: fingrow
    password: fingrow123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    show-sql: true
  
# SQL
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
server:
  port: 8080

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
  packages-to-scan: com.fingrow

# JWT 설정
jwt:
  secret: fingrow-jwt-secret-key-for-token-generation-and-validation-2024
  access-token-validity-in-seconds: 3600  # 1시간
  refresh-token-validity-in-seconds: 1209600  # 2주

# OAuth2 설정 (현재 주석 처리)
# spring:
#   security:
#     oauth2:
#       client:
#         registration:
#           kakao:
#             client-id: your-kakao-client-id
#             client-secret: your-kakao-client-secret
#             redirect-uri: http://localhost:3000/oauth/callback/kakao